/*
           Even Fibonacci numbers
           Problem 2 
           Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
           By starting with 1 and 2, the first 10 terms will be:

           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

           By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
           find the sum of the even-valued terms.
*/


using System;
using System.Collections.Generic;
using System.Text;

namespace SolutionLoader
{
    internal static class Problem2
    {
        public static uint SolveProblem()
        {
            uint sum = 2;
            uint i2 = 2;
            uint i1 = 1;
            uint maxLimit = 4000000;

            L0:
            var i3 = i2;
            i2 += i1;
            if (i2 <= maxLimit)
            {
                i1 = i3;
                if (i2 % 2 == 0)
                    sum += i2;
                goto L0;
            }

            return sum;
        }
    }
}
