/*
           Even Fibonacci numbers
           Problem 2 
           Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
           By starting with 1 and 2, the first 10 terms will be:

           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

           By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
           find the sum of the even-valued terms.
*/


using System;
using System.Collections.Generic;
using System.Text;

namespace SolutionLoader
{
    internal static class Problem2
    {
        public static uint SolveProblem()
        {
            uint sum = 2;
            uint currentFibonacciNumber = 2;
            uint previousFibonacciNumber = 1;
            uint maxLimit = 4000000000;

            IterateFibonacci:
            var lastCurrentFibonacciNumber = currentFibonacciNumber;
            currentFibonacciNumber += previousFibonacciNumber;
            if (currentFibonacciNumber <= maxLimit)
            {
                previousFibonacciNumber = lastCurrentFibonacciNumber;
                if (currentFibonacciNumber % 2 == 0)
                    sum += currentFibonacciNumber;
                goto IterateFibonacci;
            }

            return sum;
        }
    }
}
